### ISSUE TITLE
No inward/outward?

### ISSUE THREAD

**Issue by DemenzEchtbaer** [dcqin17/dragonking#17]
Hello again and thank you again for the cool package.

Inward or outward test does not work as in the example (dk.inward, etc. -> module 'dragonking' has no attribute 'inward'), and my IDE does not see them as methods in either DK_test or moreDKtests: what am I missing?

**Comment by orwinmc** [comment]
This package was still under development likely when this comment was made.

I have not touched this repo in quite a while, but feel free to fork it and make any adjustments. Thanks!

**Comment by DemenzEchtbaer** [comment]
Hey there, I haven't encountered Dragon Kings for a while, but I will definitely have a look at the code and let you know if they come back growling.

Cheer and thanks again!
